<option value="ADLAON">ADLAON</option>
<option value="AGSUNGOT">AGSUNGOT</option>
<option value="APAS">APAS</option>
<option value="BABAG">BABAG</option>
<option value="BACAYAN">BACAYAN</option>
<option value="BANILAD">BANILAD</option>
<option value="BASAK SAN NICOLAS">BASAK SAN NICOLAS</option>
<option value="BASAK-PARDO">BASAK-PARDO</option>
<option value="BINALIW">BINALIW</option>
<option value="BONBON">BONBON</option>
<option value="BUDLA-AN">BUDLA-AN</option>
<option value="BUHISAN">BUHISAN</option>
<option value="BULACAO PARDO">BULACAO PARDO</option>
<option value="BUOT-TAUP">BUOT-TAUP</option>
<option value="BUSAY">BUSAY</option>
<option value="CALAMBA">CALAMBA</option>
<option value="CAMBINOCOT">CAMBINOCOT</option>
<option value="CAPITOL SITE">CAPITOL SITE</option>
<option value="CARRETA">CARRETA</option>
<option value="COGON PARDO">COGON PARDO</option>
<option value="COGON RAMOS">COGON RAMOS</option>
<option value="DAY-AS">DAY-AS</option>
<option value="DULJO-FATIMA">DULJO-FATIMA</option>
<option value="GUADALUPE">GUADALUPE</option>
<option value="GUBA">GUBA</option>
<option value="HIPODROMO">HIPODROMO</option>
<option value="INAYAWAN">INAYAWAN</option>
<option value="KALUBIHAN">KALUBIHAN</option>
<option value="KALUNASAN">KALUNASAN</option>
<option value="KAMAGAYAN">KAMAGAYAN</option>
<option value="KAMPUTHAW (CAMPUTHAW)">KAMPUTHAW (CAMPUTHAW)</option>
<option value="KASAMBAGAN">KASAMBAGAN</option>
<option value="KINASANG-AN">KINASANG-AN</option>
<option value="LABANGON">LABANGON</option>
<option value="LAHUG">LAHUG</option>
<option value="LOREGA SAN MIGUEL">LOREGA SAN MIGUEL</option>
<option value="LUSARAN">LUSARAN</option>
<option value="LUZ">LUZ</option>
<option value="MABINI">MABINI</option>
<option value="MABOLO PROPER">MABOLO PROPER</option>
<option value="MALUBOG">MALUBOG</option>
<option value="MAMBALING">MAMBALING</option>
<option value="PAHINA CENTRAL">PAHINA CENTRAL</option>
<option value="PAHINA SAN NICOLAS">PAHINA SAN NICOLAS</option>
<option value="PAMUTAN">PAMUTAN</option>
<option value="PARIAN">PARIAN</option>
<option value="PARIL">PARIL</option>
<option value="PASIL">PASIL</option>
<option value="PIT-OS">PIT-OS</option>
<option value="POBLACION PARDO">POBLACION PARDO</option>
<option value="PULANGBATO">PULANGBATO</option>
<option value="PUNG-OL SIBUGAY">PUNG-OL SIBUGAY</option>
<option value="PUNTA PRINCESA">PUNTA PRINCESA</option>
<option value="QUIOT PARDO">QUIOT PARDO</option>
<option value="SAMBAG I">SAMBAG I</option>
<option value="SAMBAG II">SAMBAG II</option>
<option value="SAN ANTONIO">SAN ANTONIO</option>
<option value="SAN JOSE">SAN JOSE</option>
<option value="SAN NICOLAS PROPER">SAN NICOLAS PROPER</option>
<option value="SAN ROQUE">SAN ROQUE</option>
<option value="SANTA CRUZ">SANTA CRUZ</option>
<option value="SANTO NIÑO">SANTO NIÑO</option>
<option value="SAPANGDAKO">SAPANGDAKO</option>
<option value="SAWANG CALERO">SAWANG CALERO</option>
<option value="SINSIN">SINSIN</option>
<option value="SIRAO">SIRAO</option>
<option value="SUBA">SUBA</option>
<option value="SUDLON I">SUDLON I</option>
<option value="SUDLON II">SUDLON II</option>
<option value="T. PADILLA">T. PADILLA</option>
<option value="TABUNAN">TABUNAN</option>
<option value="TAGBA-O">TAGBA-O</option>
<option value="TALAMBAN">TALAMBAN</option>
<option value="TAPTAP">TAPTAP</option>
<option value="TEJERO">TEJERO</option>
<option value="TINAGO">TINAGO</option>
<option value="TISA">TISA</option>
<option value="TOONG">TOONG</option>
<option value="ZAPATERA">ZAPATERA</option>
