{{-- <option value="THE PURPOSE OF SECURING BUSINESS PERMIT">THE PURPOSE OF SECURING BUSINESS PERMIT</option>
<option value="NEW BUSINESS PERMIT">NEW BUSINESS PERMIT</option>
<option value="OCCUPANCY PERMIT">OCCUPANCY PERMIT</option>
<option value="RENEWAL OF BUSINESS PERMIT">RENEWAL OF BUSINESS PERMIT</option>
<option value="RENEWAL OF BUSINESS PERMIT/TESDA ACCREDITATION">RENEWAL OF BUSINESS PERMIT/TESDA ACCREDITATION</option>
<option value="RENEWAL OF BUSINESS PERMIT/DOT ACCREDITATION">RENEWAL OF BUSINESS PERMIT/DOT ACCREDITATION</option>
<option value="PEZA OCCUPANCY PERMIT">PEZA OCCUPANCY PERMIT</option>
<option value="ANNUAL INSPECTION OF PEZA CERTIFICATE">ANNUAL INSPECTION OF PEZA CERTIFICATE</option> --}}
