<option value="FSIF(NBP) - FIRE SAFETY INSPECTION FEE - BFP-06">FSIF(NBP) - FIRE SAFETY INSPECTION FEE - BFP-06</option>
<option value="FSIF(RBP) - FIRE SAFETY INSPECTION FEE - BFP-06" selected="">FSIF(RBP) - FIRE SAFETY INSPECTION FEE -
    BFP-06</option>
<option value="FSIF(OCC) - FIRE SAFETY INSPECTION FEE - BFP-06">FSIF(OCC) - FIRE SAFETY INSPECTION FEE - BFP-06</option>
<option value="FSIF(ACCREDITATION) - FIRE SAFETY INSPECTION FEE - BFP-06">FSIF(ACCREDITATION) - FIRE SAFETY INSPECTION
    FEE - BFP-06</option>
<option value="FCCT - FIRE CODE CONSTRUCTION TAX - BFP-01">FCCT - FIRE CODE CONSTRUCTION TAX - BFP-01</option>
<option value="FCRT - FIRE CODE REALTY TAX - BFP-02">FCRT - FIRE CODE REALTY TAX - BFP-02</option>
<option value="FCPret - FIRE CODE PREMIUM TAX - BFP-03">FCPret - FIRE CODE PREMIUM TAX - BFP-03</option>
<option value="FCProt - FIRE CODE PROCEEDS TAX - BFP-04">FCProt - FIRE CODE PROCEEDS TAX - BFP-04</option>
<option value="FCST - FIRE CODE SALES TAX - BFP-05">FCST - FIRE CODE SALES TAX - BFP-05</option>
<option value="STO - STORAGE CLEARANCE FEE - BFP-07">STO - STORAGE CLEARANCE FEE - BFP-07</option>
<option value="CON - CONVEYANCE CLEARANCE FEE - BFP-08">CON - CONVEYANCE CLEARANCE FEE - BFP-08</option>
<option value="INST - INSTALLATION CLEARANCE FEE - BFP-09">INST - INSTALLATION CLEARANCE FEE - BFP-09</option>
<option value="FCAF - FIRE CODE ADMINISTRATIVE FINES - BFP-11">FCAF - FIRE CODE ADMINISTRATIVE FINES - BFP-11</option>
<option value="OTHERS(FD) - OTHERS (FIRE DRILL) - BFP-10">OTHERS(FD) - OTHERS (FIRE DRILL) - BFP-10</option>
<option value="OTHERS(FWD) - OTHERS (FIREWORKS DISPLAY) - BFP-10">OTHERS(FWD) - OTHERS (FIREWORKS DISPLAY) - BFP-10
</option>
<option value="OTHERS(HW) - OTHERS (HOTWORKS) - BFP-10">OTHERS(HW) - OTHERS (HOTWORKS) - BFP-10</option>
<option value="OTHERS(FG) - OTHERS (FOGGING) - BFP-10">OTHERS(FG) - OTHERS (FOGGING) - BFP-10</option>
<option value="OTHERS(L/U) - OTHERS (LOADING/UNLOADING) - BFP-10">OTHERS(L/U) - OTHERS (LOADING/UNLOADING) - BFP-10
</option>
<option value="OTHERS(SF) - OTHERS (STANDBY FIRE TRUCK) - BFP-10">OTHERS(SF) - OTHERS (STANDBY FIRE TRUCK) - BFP-10
</option>
<option value="OTHERS(FC) - OTHERS (FIRE CERTIFICATE) - BFP-10">OTHERS(FC) - OTHERS (FIRE CERTIFICATE) - BFP-10</option>
<option value="OTHERS(A/CTC) - OTHERS (AUTHENTICATION/CTC) - BFP-10">OTHERS(A/CTC) - OTHERS (AUTHENTICATION/CTC) -
    BFP-10</option>
<option value="FCCT/Hotworks - FCCT/Hotworks - BFP-01/10">FCCT/HOTWORKS - FCCT/HOTWORKS - BFP-01/10</option>
