<option value="RESIDENTIAL">RESIDENTIAL</option>
<option value="ASSEMBLY">ASSEMBLY</option>
<option value="HEALTH CARE">HEALTH CARE</option>
<option value="EDUCATIONAL">EDUCATIONAL</option>
<option value="MERCANTILE">MERCANTILE</option>
<option value="DETENTION AND CORRECTIONAL">DETENTION AND CORRECTIONAL</option>
<option value="INDUSTRIAL">INDUSTRIAL</option>
<option value="BUSINESS">BUSINESS</option>
<option value="STORAGE">STORAGE</option>
<option value="OTHERS">OTHERS</option>
