const barangays = [
    "ADLAON",
    "AGSUNGOT",
    "APAS",
    "BABAG",
    "BACAYAN",
    "BANILAD",
    "BASAK SAN NICOLAS",
    "BASAK-PARDO",
    "BINALIW",
    "BONBON",
    "BUDLA-AN",
    "BUHISAN",
    "BULACAO PARDO",
    "BUOT-TAUP",
    "BUSAY",
    "CALAMBA",
    "CAMBINOCOT",
    "CAPITOL SITE",
    "CARRETA",
    "COGON PARDO",
    "COGON RAMOS",
    "DAY-AS",
    "DULJO-FATIMA",
    "GUADALUPE",
    "GUBA",
    "HIPODROMO",
    "INAYAWAN",
    "KALUBIHAN",
    "KALUNASAN",
    "KAMAGAYAN",
    "KAMPUTHAW (CAMPUTHAW)",
    "KASAMBAGAN",
    "KINASANG-AN",
    "LABANGON",
    "LAHUG",
    "LOREGA SAN MIGUEL",
    "LUSARAN",
    "LUZ",
    "MABINI",
    "MABOLO PROPER",
    "MALUBOG",
    "MAMBALING",
    "PAHINA CENTRAL",
    "PAHINA SAN NICOLAS",
    "PAMUTAN",
    "PARIAN",
    "PARIL",
    "PASIL",
    "PIT-OS",
    "POBLACION PARDO",
    "PULANGBATO",
    "PUNG-OL SIBUGAY",
    "PUNTA PRINCESA",
    "QUIOT PARDO",
    "SAMBAG I",
    "SAMBAG II",
    "SAN ANTONIO",
    "SAN JOSE",
    "SAN NICOLAS PROPER",
    "SAN ROQUE",
    "SANTA CRUZ",
    "SANTO NIÑO",
    "SAPANGDAKO",
    "SAWANG CALERO",
    "SINSIN",
    "SIRAO",
    "SUBA",
    "SUDLON I",
    "SUDLON II",
    "T. PADILLA",
    "TABUNAN",
    "TAGBA-O",
    "TALAMBAN",
    "TAPTAP",
    "TEJERO",
    "TINAGO",
    "TISA",
    "TOONG",
    "ZAPATERA"
  ];

  export default barangays;