const issuedFor = {
    NEW: ["THE PURPOSE OF SECURING BUSINESS PERMIT", "NEW BUSINESS PERMIT"],
    RENEWAL: ["RENEWAL OF BUSINESS PERMIT"],
    OTHER: [
        "RENEWAL OF BUSINESS PERMIT/TESDA ACCREDITATION",
        "RENEWAL OF BUSINESS PERMIT/DOT ACCREDITATION",
        "ANNUAL INSPECTION OF PEZA CERTIFICATE",
    ],
    OCCUPANCY: ["PEZA OCCUPANCY PERMIT", "OCCUPANCY PERMIT"],
};

export default issuedFor;
